"""prueba sin filtro

Revision ID: a9c7fe520e71
Revises: 74c3bf23a629
Create Date: 2025-07-10 22:17:57.703325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c7fe520e71'
down_revision: Union[str, None] = '74c3bf23a629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_asociaciones_id'), 'asociaciones', ['id'], unique=False, schema='public')
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('edad_minima', sa.Integer(), nullable=False),
    sa.Column('edad_maxima', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('sets_por_partido', sa.Integer(), nullable=False),
    sa.Column('puntos_por_set', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_categorias_id'), 'categorias', ['id'], unique=False, schema='public')
    op.create_table('torneos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_inicio_inscripcion', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin_inscripcion', sa.DateTime(), nullable=False),
    sa.Column('fecha_inicio_competencia', sa.DateTime(), nullable=False),
    sa.Column('mesas_disponibles', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_torneos_id'), 'torneos', ['id'], unique=False, schema='public')
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['torneo_id'], ['public.torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_grupos_id'), 'grupos', ['id'], unique=False, schema='public')
    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('asociacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asociacion_id'], ['public.asociaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_jugadores_id'), 'jugadores', ['id'], unique=False, schema='public')
    op.create_table('rondas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['torneo_id'], ['public.torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_rondas_id'), 'rondas', ['id'], unique=False, schema='public')
    op.create_table('torneos_categorias',
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['public.categorias.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['public.torneos.id'], ),
    sa.PrimaryKeyConstraint('torneo_id', 'categoria_id'),
    schema='public'
    )
    op.create_table('equipos_dobles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador1_id', sa.Integer(), nullable=False),
    sa.Column('jugador2_id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['public.categorias.id'], ),
    sa.ForeignKeyConstraint(['jugador1_id'], ['public.jugadores.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['public.jugadores.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['public.torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_equipos_dobles_id'), 'equipos_dobles', ['id'], unique=False, schema='public')
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=True),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['public.categorias.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['public.jugadores.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['public.torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_participantes_id'), 'participantes', ['id'], unique=False, schema='public')
    op.create_table('llaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ronda_id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('es_bye', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['public.equipos_dobles.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['public.participantes.id'], ),
    sa.ForeignKeyConstraint(['ronda_id'], ['public.rondas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_llaves_id'), 'llaves', ['id'], unique=False, schema='public')
    op.create_table('participantes_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['public.grupos.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['public.participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_participantes_grupos_id'), 'participantes_grupos', ['id'], unique=False, schema='public')
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=False),
    sa.Column('mesa', sa.Integer(), nullable=False),
    sa.Column('jugador1_id', sa.Integer(), nullable=True),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('equipo1_id', sa.Integer(), nullable=True),
    sa.Column('equipo2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo1_id'], ['public.equipos_dobles.id'], ),
    sa.ForeignKeyConstraint(['equipo2_id'], ['public.equipos_dobles.id'], ),
    sa.ForeignKeyConstraint(['jugador1_id'], ['public.jugadores.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['public.jugadores.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['public.torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_partidos_id'), 'partidos', ['id'], unique=False, schema='public')
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('numero_set', sa.Integer(), nullable=False),
    sa.Column('puntos_jugador1', sa.Integer(), nullable=False),
    sa.Column('puntos_jugador2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['public.partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sets_id'), 'sets', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_sets_id'), table_name='sets', schema='public')
    op.drop_table('sets', schema='public')
    op.drop_index(op.f('ix_public_partidos_id'), table_name='partidos', schema='public')
    op.drop_table('partidos', schema='public')
    op.drop_index(op.f('ix_public_participantes_grupos_id'), table_name='participantes_grupos', schema='public')
    op.drop_table('participantes_grupos', schema='public')
    op.drop_index(op.f('ix_public_llaves_id'), table_name='llaves', schema='public')
    op.drop_table('llaves', schema='public')
    op.drop_index(op.f('ix_public_participantes_id'), table_name='participantes', schema='public')
    op.drop_table('participantes', schema='public')
    op.drop_index(op.f('ix_public_equipos_dobles_id'), table_name='equipos_dobles', schema='public')
    op.drop_table('equipos_dobles', schema='public')
    op.drop_table('torneos_categorias', schema='public')
    op.drop_index(op.f('ix_public_rondas_id'), table_name='rondas', schema='public')
    op.drop_table('rondas', schema='public')
    op.drop_index(op.f('ix_public_jugadores_id'), table_name='jugadores', schema='public')
    op.drop_table('jugadores', schema='public')
    op.drop_index(op.f('ix_public_grupos_id'), table_name='grupos', schema='public')
    op.drop_table('grupos', schema='public')
    op.drop_index(op.f('ix_public_torneos_id'), table_name='torneos', schema='public')
    op.drop_table('torneos', schema='public')
    op.drop_index(op.f('ix_public_categorias_id'), table_name='categorias', schema='public')
    op.drop_table('categorias', schema='public')
    op.drop_index(op.f('ix_public_asociaciones_id'), table_name='asociaciones', schema='public')
    op.drop_table('asociaciones', schema='public')
    # ### end Alembic commands ###
